# Generated by Django 4.2.6 on 2023-10-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=4)),
                (
                    "groups",
                    models.ManyToManyField(related_name="students", to="groups.group"),
                ),
            ],
        ),
    ]
