# Generated by Django 4.2.6 on 2023-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("students", "0002_alter_student_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="groups",
            field=models.ManyToManyField(related_name="students", to="groups.group"),
        ),
    ]
