# Generated by Django 4.2.6 on 2023-10-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("students", "0003_alter_student_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="groups.group"
            ),
        ),
    ]
