# Generated by Django 4.2.6 on 2023-10-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_student_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
