# Generated by Django 4.2.6 on 2023-10-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=100, verbose_name="Назва предмету"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="ПІБ"),
                ),
                (
                    "birth_date",
                    models.DateField(default="", verbose_name="Дата народження"),
                ),
                (
                    "subjects",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="teachers.subject",
                        verbose_name="Предмети",
                    ),
                ),
            ],
        ),
    ]
