# Generated by Django 4.2.6 on 2023-10-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="teachers.subject",
                verbose_name="Предмети",
            ),
        ),
    ]
