# Generated by Django 4.2.6 on 2023-10-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_alter_teacher_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teachers.subject",
                verbose_name="Предмети",
            ),
        ),
    ]
